# Generated by Django 3.1 on 2021-01-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210131_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pswRegistration',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
