# Generated by Django 3.1 on 2021-03-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_client_pswregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='codePostale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='complementAdresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(default='', max_length=30),
        ),
    ]
