# Generated by Django 3.1 on 2021-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210403_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='logged_in',
        ),
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.CharField(default='home', max_length=50),
            preserve_default=False,
        ),
    ]
