# Generated by Django 3.1 on 2021-04-03 20:48

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210403_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='type',
        ),
        migrations.AddField(
            model_name='commande',
            name='service',
            field=models.CharField(choices=[(home.models.TypesOfServices['Pharmacy'], 'Pharmacy'), (home.models.TypesOfServices['Food'], 'Food'), (home.models.TypesOfServices['Gift'], 'Gift'), (home.models.TypesOfServices['Race'], 'Race'), (home.models.TypesOfServices['Service'], 'Service'), (home.models.TypesOfServices['Home'], 'Home')], default=home.models.TypesOfServices['Home'], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='service',
            field=models.CharField(choices=[(home.models.TypesOfServices['Pharmacy'], 'Pharmacy'), (home.models.TypesOfServices['Food'], 'Food'), (home.models.TypesOfServices['Gift'], 'Gift'), (home.models.TypesOfServices['Race'], 'Race'), (home.models.TypesOfServices['Service'], 'Service'), (home.models.TypesOfServices['Home'], 'Home')], default=home.models.TypesOfServices['Home'], max_length=20),
        ),
    ]
